#!/bin/bash

while [[ True ]]
do

echo "enter your name:"
read name

if [[ -z $name ]]
then

break
else
echo $name
echo "enter your age:"
read age
fi

if [[ $age -eq 0 ]]
then
echo "bye"
break

elif [[ $age -gt 0 && $age -le 16 ]]
then

echo "$name, your group is child"

elif [[ $age -gt 16 && $age -le 25 ]]
then

echo "$name, your group is youth"

elif [[ $age -gt 25 ]]
then

echo "$name, your group is adult"

fi

done
